# fly.toml app configuration file generated for autorouting-dataset on 2024-12-08T15:54:39-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'autorouting-dataset'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
