name: Benchmark Algorithms

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
      
      - name: Build
        run: bun run build

      - name: Run benchmarks
        run: bun run scripts/benchmark.ts

      - name: Commit benchmark results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add BENCHMARKS.md
          git commit -m "Update benchmark results" || echo "No changes to commit"
          git push
